##Desafio de Matemática para Data Science

1. Conjuntos e Lógica:
2. Álgebra linear: multiplicação de vetores e matrizes
3. Funções e polinômios
4. Cáculo: Derivadas e otimização
5. Matemática essencial: Potenciação e logarítimos

In [ ]:
# Bibliotecas
import numpy as np


1. Conjuntos e Lógica

Em uma equipe de tecnologia, um grupo de 30 profissionais utiliza ferramentas de análise. Sabe-se que 18 usam Python, 15 usam R, e 6 usam ambas as linguagens.

Quantos profissionais dessa equipe não usam nenhuma das duas linguagens?

In [ ]:
# Variáveis
equipe = 30
python_R = 6
python = 18 - python_R
Ling_R = 15 - python_R

outros = equipe - python - Ling_R - python_R
print(f'Não programam e nenhuma linguagem é: {outros}')


Não programam e nenhuma linguagem é: 3


2. Álgebra Linear

Dada a matriz $A = \begin{bmatrix} 2 & 1 \\ 0 & 3 \end{bmatrix}$ e o vetor $v = \begin{bmatrix} 1 \\ 2 \end{bmatrix}$, qual é o resultado da multiplicação da matriz pelo vetor ($A \cdot v$)?

In [ ]:
# Variáveis
matrix_A = np.array([[2, 1],[1, 3]])
vetor_V = np.array([[1],[2]])

# Multiplicação

print(f'Matrix A:\n {matrix_A}')
print(f"Vetor V: \n {vetor_V}")
print(f'Multiplicação da Matrix A pelo vetor V:\n {matrix_A @ vetor_V}')

Matrix A:
 [[2 1]
 [1 3]]
Vetor V: 
 [[1]
 [2]]
Multiplicação da Matrix A pelo vetor V:
 [[4]
 [7]]


3. Funções e Polinômios

Uma empresa de tecnologia modelou seu custo de processamento (em milhares de reais) em função do volume de dados processados $x$ (em terabytes) através da função quadrática

:$$C(x) = x^2 - 6x + 10$$

Qual é o volume de dados $x$ que minimiza o custo de processamento dessa empresa?

In [1]:
# Coeficientes da função quadrática C(x) = x^2 - 6x + 10
a = 1
b = -6
c = 10

# O volume de dados x que minimiza o custo é dado por x = -b / (2a)
x_min = -b / (2 * a)

print(f'O volume de dados x que minimiza o custo é: {x_min}')

O volume de dados x que minimiza o custo é: 3.0


4. Cálculo (Derivadas e Otimização)

Dada a função de custo $f(w) = 3w^2 - 12w + 5$, qual é o valor de $w$ que zera a derivada da função ($f'(w) = 0$), ponto que representa o mínimo da função em um processo de gradiente?


In [2]:
# Função de custo f(w) = 3w^2 - 12w + 5

# A derivada da função é f'(w) = 6w - 12
# Para encontrar o mínimo, igualamos a derivada a zero: 6w - 12 = 0

# Resolvendo para w:
w = 12 / 6

print(f'O valor de w que zera a derivada da função é: {w}')

O valor de w que zera a derivada da função é: 2.0


5. Matemática Essencial (Potenciação e Logaritmos)

Simplificando a expressão com logaritmos e potências que você revisou no código: sabendo que $\log_3(2187) = 7$ (porque $3^7 = 2187$), qual é o resultado da operação de potenciação $2^3 \cdot 2^4$ utilizando as propriedades de bases iguais?



In [ ]:
# Variáveis:

pot1 = 2**3
pot2 = 2**4
potR = 2**(3+4)

print(f'Primeira Potência 2^3: {pot1}')
print(f'Segunda Potência 2^4: {pot2}')
print(f'Potência resultante 2^7: {potR}')

Primeira Potência 2^3: 8
Segunda Potência 2^4: 16
Potência resultante 2^7: 128


In [3]:
import math

# Operação de Logaritmo: log base 3 de 2187
log_result = math.log(2187, 3)
print(f'log_3(2187) = {log_result}')

# Operação de Potenciação: 2^3 * 2^4 usando propriedades de bases iguais
# Isso é equivalente a 2^(3+4) = 2^7
pow_result_base3 = math.pow(2, 3)
pow_result_base4 = math.pow(2, 4)
pow_result_product = pow_result_base3 * pow_result_base4
print(f'2^3 * 2^4 = {pow_result_product}')

# Ou diretamente 2^(3+4)
pow_result_combined = math.pow(2, 3 + 4)
print(f'2^(3+4) = {pow_result_combined}')

log_3(2187) = 7.0
2^3 * 2^4 = 128.0
2^(3+4) = 128.0
