# Álgebra Linear

1. Sistemas de Coordenadas;
2. Ponto;
3. Vetor:
    R2 = (x,y)
    R3 = (x, y, x)
    Rn (x1, x2, ... xn);
4. Vetor
4.1 Operações com vetores
5. Matrizes
5.1. Operações com matrizes
5.2. Determinantes


In [3]:
# 4.1 Operações com vetores
import numpy as np

v = np.array ([3,4])
u = np.array ([ 2, -3])
e = 2 # Multiplicação por escalar

print(f'Vetores: v {v} e U {u}')
print(f'Soma: {v + u}')
print(f'Subtração: { v - u}')
print(f'Multiplicação por escalar: {e * u}')
print(f'Módulo do vetor V:  {np.linalg.norm(v)}')

Vetores: v [3 4] e U [ 2 -3]
Soma: [5 1]
Subtração: [1 7]
Multiplicação por escalar: [ 4 -6]
Módulo do vetor V:  5.0


In [4]:
# 5. Matrizes

matrix = np.array([[3, -2,], [1, 0]])
m_linha = np.array([1,3,8])
m_coluna = np.array([[10],
                     [20]])

# Cria uma matriz 3x3
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Com reshape
transf_C = m_linha.reshape(-1,1)

# Cria uma matriz nula de 3 linhas e 4 colunas
matriz_nula = np.zeros((3, 4), dtype=int)

# Cria uma matriz identidade 3x3 com números inteiros
matriz_identidade = np.eye(3, dtype=int)

print(f'1. Matriz_1: \n {matrix}')

1. Matriz_1: 
 [[ 3 -2]
 [ 1  0]]


In [5]:
print(f'\n 2. Matriz linha: {m_linha}')


 2. Matriz linha: [1 3 8]


In [6]:
print(f'\n 3. Matriz Coluna \n {m_coluna}')


 3. Matriz Coluna 
 [[10]
 [20]]


In [7]:
print(f'\n 3.1 Transfomação de matriz linha por coluna:\n {transf_C}')


 3.1 Transfomação de matriz linha por coluna:
 [[1]
 [3]
 [8]]


In [8]:
print(f'\n 4.  Matriz Quadrada: \n { matriz}')


 4.  Matriz Quadrada: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(f'\n 5. Matriz Nula: \n {matriz_nula}')


 5. Matriz Nula: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
print(f'\n 5. Matriz Nula: \n {matriz_nula}')


 5. Matriz Nula: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [11]:
print(f' \n 6. Matriz identidade: \n {matriz_identidade}')

 
 6. Matriz identidade: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [12]:
# Operações com matrizes

matriz_a = np.array([[ 1, 4, 2], [ -2, 1, 0]])
matriz_b = np.array([[ 4, -3, 1], [ 5, 0, 2]])
matriz_c = np.array([[ 2, 0, 3], [ 3, 2, 4]])

print('Operações com matrizes')
# a + b = b = a
print(f'1. Comutativa: \n { matriz_a + matriz_b}')


Operações com matrizes
1. Comutativa: 
 [[5 1 3]
 [3 1 2]]


In [13]:
print(f'2. Comutativa: \n { (matriz_a + matriz_b)* matriz_c}')
# (a+b) + c = a (b+c)

2. Comutativa: 
 [[10  0  9]
 [ 9  2  8]]


In [14]:
print(f'3. Elemento oposto:\n { matriz_a +(-matriz_a) }')
# a + (-a) = -a + a = 0

3. Elemento oposto:
 [[0 0 0]
 [0 0 0]]


In [15]:
print(f'Elemento: \n { matriz_a + 0 }')
# a + 0 = 0 + a = a


Elemento: 
 [[ 1  4  2]
 [-2  1  0]]


In [16]:
print(f'1. Comutativa: \n { matriz_a - matriz_b}')


1. Comutativa: 
 [[-3  7  1]
 [-7  1 -2]]


In [17]:
matriz_aT = matriz_a.T
print(f'Matriz Transposta: \n {matriz_aT}')

Matriz Transposta: 
 [[ 1 -2]
 [ 4  1]
 [ 2  0]]


In [18]:
# Multiplicação de Matrizes
# O números de colunas A precisar ser igual ao número de linhas de B

# 1. Criando a matriz A com formato (2, 3)
matriz_A = np.array([
    [4, 5, 6]
])

# 2. Criando a transposta com formato (3, 2)
matriz_aT = matriz_A.T

# 3. EXIBINDO AS MATRIZES
print(f'Matriz A (shape {matriz_A.shape}):\n{matriz_A}\n')
print(f'Matriz Transposta (shape {matriz_aT.shape}):\n{matriz_aT}\n')

# -------------------------------------------------------------
# O SEGREDO ESTÁ AQUI: Use obrigatoriamente o símbolo '@'
# -------------------------------------------------------------
resultado = matriz_A @ matriz_aT

print(f'Resultado da Multiplicação Matricial (shape {resultado.shape}):\n{resultado}')


Matriz A (shape (1, 3)):
[[4 5 6]]

Matriz Transposta (shape (3, 1)):
[[4]
 [5]
 [6]]

Resultado da Multiplicação Matricial (shape (1, 1)):
[[77]]


In [19]:
# Propriedades da multiplicação (Erro)

matriz_a = np.array([[ 2, 4, 5], [ 1, -2, 0 ]])
matriz_b = np.array([[ 3, 0], [ 3, 0 ], [1, -3]])
matriz_c = np.array([[ 1, 2, 3], [ 0, -1, 2 ]])

print(f'Matriz A: \n {matriz_a}')

print(f'Matriz B: \n {matriz_b}')

print(f'Matriz C: \n {matriz_c}')

Matriz A: 
 [[ 2  4  5]
 [ 1 -2  0]]
Matriz B: 
 [[ 3  0]
 [ 3  0]
 [ 1 -3]]
Matriz C: 
 [[ 1  2  3]
 [ 0 -1  2]]


In [20]:
# Não é comulativa a x b diferente de b x a

print(f'Multiplicação de A e B: \n {matriz_a @ matriz_b}')

print(f'\n Multiplicação de B e A: \n {matriz_b @ matriz_a}')


Multiplicação de A e B: 
 [[ 23 -15]
 [ -3   0]]

 Multiplicação de B e A: 
 [[ 6 12 15]
 [ 6 12 15]
 [-1 10  5]]


In [21]:
# Assossiativa: (a x b)x c = a x(b x c) - São iguais

print(f'Multiplicação de (A x B) x c: \n {(matriz_a @ matriz_b) @ matriz_c}')

print(f'Multiplicação de A x (B x C): \n {matriz_a @ (matriz_b @ matriz_c)}')



Multiplicação de (A x B) x c: 
 [[23 61 39]
 [-3 -6 -9]]
Multiplicação de A x (B x C): 
 [[23 61 39]
 [-3 -6 -9]]


In [23]:
# X x ( a + c ) = b x a + c x a
# A correção é feita usando matrizes com dimensões compatíveis para a adição.
# `matriz_a` e `matriz_c` têm ambos o formato (2,3), o que permite a adição.
# `matriz_x` também será convertida para um array NumPy com o formato (2,3).

matriz_x_np = np.array([[2, -3, 0], [1, 0, 2]])

# Realizando a operação com matrizes de dimensões compatíveis
# O operador '*' realiza multiplicação elemento a elemento.
# Usamos 'matriz_a + matriz_c' pois ambos têm dimensão (2,3).
print(f'Multiplicação elemento a elemento de X com (A + C): \n {matriz_x_np * (matriz_a + matriz_c)}')


Multiplicação elemento a elemento de X com (A + C): 
 [[  6 -18   0]
 [  1   0   4]]


In [ ]:
# Elemento a x ln = ln. a = a

print(f'Elemento neutro: \n {matriz_a * 1}')

In [ ]:
# Determinantes

# 1. Gerando a matriz quadrada (2x2) que você calculou antes
matriz_quadrada = matriz_a @ matriz_a.T

# 2. Calculando o determinante
determinante = np.linalg.det(matriz_quadrada)

print(f'Matriz Quadrada:\n{matriz_quadrada}\n')
print(f'Determinante da Matriz: {determinante:.2f}')
